import { Roboto } from 'next/font/google'
import { Toaster } from 'react-hot-toast';
import Header from '../components/layout/Header';
import './globals.css'
import Footer from '../components/layout/Footer';
import { Provider } from '@/components/Providers';


const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
 
  
  return (
      <html lang="en">
          <body className={`${roboto.className} min-h-screen flex flex-col overflow-x-hidden `}>
              <Provider>
                  <Header />
                  <main className="container grow flex flex-col justify-center">{children}</main>
                  <Toaster position="top-center" />
                  <Footer />
              </Provider>
          </body>
      </html>
  );
}
